### ISSUE TITLE
Add "slo alert" type to monitor enum

### ISSUE THREAD

**Issue by Anton0** [DataDog/datadog-cloudformation-resources#122]
The list of acceptible types in the Datadog Monitor resource doesn't include `slo alert` which was added in an open beta (see blog in Additional Content) based on the fact that the slo alert has been incorporated in other supported Datadog resources such as the go-sdk and terraform it would be great to have it as a cloudformation resource option as well.

https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/datadog-monitors-monitor.json#L183-L196

**Describe the solution you'd like**

Allow `Datadog::Monitors::Monitor` to accept `slo alert` as as a Type

Given it seems like a straight forward change I'll submit a PR shortly.

**Describe alternatives you've considered**

Writing my own cloudformation resource I suppose?

**Additional context**

The datadog API now supports _in beta_ the ability to create error budget alarms via the API

https://docs.datadoghq.com/monitors/service_level_objectives/error_budget/#api-and-terraform

**Comment by Anton0** [comment]
Looks like this (though not listed in the CHANGELOG) was released in [4.0.0](https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/CHANGELOG.md#400--2021-06-28)

Thanks! 🎉

**Comment by iwt-dennyschaefer** [comment]
He @andrewlock :wave: 

How about that you are going to create the Changelog entry for that? ;)
