### ISSUE TITLE
Cannot change existing monitors after upgrade

### ISSUE THREAD

**Issue by sunshineo** [DataDog/datadog-cloudformation-resources#133]
After upgrade to 3.0.0 we cannot change the existing monitors. We get the problem that the physical id is not int, it is in a scientific format
```
Resource handler returned message: "invalid literal for int() with base 10: '3.0149123E7' (ValueError)" (RequestToken: abe04bbd-2b08-2e4b-f864-2ff2063c476a, HandlerErrorCode: InvalidRequest)
```
We cannot delete it either unless do a manual delete on the CloudFormation UI and skip these resources

![image](https://user-images.githubusercontent.com/1072766/119188653-cd911a00-ba2f-11eb-9c4e-69bee8e1c070.png)

**Comment by sunshineo** [comment]
Can someone have a look?

**Comment by ian28223** [comment]
> Can someone have a look?

I believe this issue has been fixed in 3.0.0b1 or the latest 4.0.0
- https://github.com/DataDog/datadog-cloudformation-resources/issues/80#issuecomment-719642538
- https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/CHANGELOG.md#300b1--2020-10-30

**Comment by sunshineo** [comment]
We will try

**Comment by sunshineo** [comment]
After upgrade to 4.0.0, we cannot deploy our monitor. I filed a separated issue https://github.com/DataDog/datadog-cloudformation-resources/issues/158

**Comment by calorie** [comment]
I have same issue in 4.1.0.

**Comment by skarimo** [comment]
👋  This should be handled with the changes mentioned here: https://github.com/DataDog/datadog-cloudformation-resources/issues/158#issuecomment-1048957271

Could you follow the upgrade steps outlined in the comment linked above and let us know. Thanks!

**Comment by gbiv** [comment]
I know this is old but the upgrade steps don't work anymore because the custom resource lambda runtimes are no longer supported for the older versions (2.x,3.x)

**Comment by skarimo** [comment]
@gbiv I just pushed up `3.1.0b2` and updated the original comment. S3 link is: `s3://datadog-cloudformation-resources/datadog-monitors-monitor/datadog-monitors-monitor-3.1.0b2.zip`

I am also going to close this issue in favor of https://github.com/DataDog/datadog-cloudformation-resources/issues/158
