### ISSUE TITLE
Cannot set monitor priority

### ISSUE THREAD

**Issue by liran90** [DataDog/datadog-cloudformation-resources#137]
Problem:
Property of "priority" that exists in Datadog monitor API  is not exposed as part of the datadog-cloudformation Monitor object

Solution:
Add a Priority field as optional integer

Additional context:
I believe this change consists of 2 small changes in the code: 
- in the ResourceModel under datadog-monitors-monitor-handler/src/models - to add a Priority field and add deserialization for it
- in the update and create handlers for monitor - to read and set the new field for monitor

**Comment by jamesadcock** [comment]
We also need this feature to be implemented

**Comment by ytsipun** [comment]
+1
