### ISSUE TITLE
Provide the CloudFormation resources also in other regions

### ISSUE THREAD

**Issue by pgarbe** [DataDog/datadog-cloudformation-resources#157]
Currently, these CloudFormation resources are only available in us-east-1. Please, make them also available in other regions (mainly eu-west-1).

**Comment by webratz** [comment]
While its not fully in CloudFormation (might work, didn't test yet) i published my notes on what worked for me for an initial test of this in eu-central-1 region at https://gist.github.com/webratz/7ff822119dee2af8ba4adb1cc5a80e3c

**Comment by pgarbe** [comment]
It's still not solved.

**Comment by skarimo** [comment]
Closing this issue as we have released the resources in the following supported regions: https://github.com/DataDog/datadog-cloudformation-resources#supported-regions
