### ISSUE TITLE
Failed to create Datadog::Monitors::Monitor / Type: event-v2 alert

### ISSUE THREAD

**Issue by itiB** [DataDog/datadog-cloudformation-resources#203]
HI, DataDog team.
We're using datadog-cloudformation-resources repo and enjoyed to manage datadog.

Last day we got inform about Datadog::Monitors::Monitor's `event alert` type resource must be update to `event-v2 alert`.
We try to update from CloudFormation, but it failed.

## **Describe the bug**

Create `Datadog::Monitors::Monitor` Type: `event-v2 alert` will be failed.

<img width="443" alt="スクリーンショット 2022-04-22 21 19 44" src="https://user-images.githubusercontent.com/24380190/165031139-b0d49ced-730b-4df0-98a9-46af24059a96.png">

## **To Reproduce**

Create sample stack and execute
  ```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RedisFailoverEventHasOccurred:
    Type: 'Datadog::Monitors::Monitor'
    Properties:
      Type: 'event-v2 alert'
      Query: "events('source:(amazon_elasticache OR Failover)').rollup('count').last('5m') > 0"
      Name: 'failover event has occurred'
      Priority: 4
      Multi: false
      Options:
        Thresholds:
          Critical: 0
          Warning: !Ref AWS::NoValue
          CriticalRecovery: !Ref AWS::NoValue
          WarningRecovery: !Ref AWS::NoValue
        NotifyNoData: false
        EvaluationDelay: 900
      Message: "id: {{event.id}}"
  ``` 

## **Expected reason**

there were no handler for `event-v2 alert` in code.
https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/datadog-monitors-monitor.json#L206-L217

## **Environment and Versions (please complete the following information):**

- Datadog Monitor 4.1.0
  - s3://datadog-cloudformation-resources/datadog-monitors-monitor/datadog-monitors-monitor-4.1.0.zip

**Comment by webratz** [comment]
I added a small MR for this with #204 - hopefully someone will take care of reviewing it soon

**Comment by itiB** [comment]
@webratz 
Thank you for your quick response!
Looking forward to being merged🌟

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/datadog-cloudformation-resources/pull/207 based off of @webratz pr. Thanks!
