### ISSUE TITLE
Missing monitor fields

### ISSUE THREAD

**Issue by huyngogia1997** [DataDog/datadog-cloudformation-resources#209]
Following the monitor resource type for cfn , I found that the monitor resource type does not support RestrictedRoles, NewGroupDelay, MinFailureDuration, RenotifyStatuses and RenotifyOccurrences  fields. Are there any things I miss? Could I add these fields and create a fork request for this?

**Comment by mecsantos** [comment]
Hi @huyngogia1997,

> Could I add these fields and create a fork request for this?

I confirmed with @therve last week that you are welcome to contribute a PR for this.

Marc

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/datadog-cloudformation-resources/pull/216
