### ISSUE TITLE
Monitor "comparison" field is missing

### ISSUE THREAD

**Issue by hlascelles** [DataDog/datadog-cloudformation-resources#211]
There is no "comparison" field in the monitors. All monitors alert when a value is "greater than (>)". There is no way to say "less than (<)".

See this file for the definition: https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/datadog-monitors-monitor.json

See the "export" from Datadog:

![image](https://user-images.githubusercontent.com/299102/170250298-bd2a95d4-b95a-4d7a-9e26-7e16579e52a1.png)

### Solution

Add the "Comparison" field, probably about here: https://github.com/DataDog/datadog-cloudformation-resources/blob/26f4473a78445b941e1b5a982f31a5b3be21a1ff/datadog-monitors-monitor-handler/datadog-monitors-monitor.json#L54

Thanks!

**Comment by hlascelles** [comment]
Related subject: https://github.com/DataDog/datadog-cloudformation-resources/issues/209

**Comment by hlascelles** [comment]
Still valid.

**Comment by skarimo** [comment]
@hlascelles thanks for opening this. What does your query look like? The comparison should be controllable by the query. For example: `"avg(last_5m):avg:kubernetes.cpu.user.total{kube_namespace:spi-ci,cluster_name:boop-dev-blue} by {pod_name} <= 2"`

Can you update your query and let us know if that works for you?

**Comment by hlascelles** [comment]
Yes, that does work, thanks! I think the comparitor is still missing from where it should be, but that alternative works fine. Thanks!
