### ISSUE TITLE
Add CloudFormation support for the renotify_statuses field

### ISSUE THREAD

**Issue by doblinger-extron** [DataDog/datadog-cloudformation-resources#212]
**Is your feature request related to a problem? Please describe.**

I would like to configure a monitor to re-alert, but **not when there is "no data"**. This is possible from the UI, the exported JSON looks like:

 `"options": {
"notify_audit": false,
"renotify_statuses": [
			"alert"
		],
		"timeout_h": 0,
		"silenced": {},
		"include_tags": true,
		"thresholds": {
			"critical": 0
		},
		"require_full_window": false,
		"notify_no_data": false,
		"renotify_interval": 480,
		"evaluation_delay": 900,
		"new_group_delay": 60
	},`

However, this option is not available with CloudFormation

**Describe the solution you'd like**

Support to not notify when "No Data" occurs.

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/datadog-cloudformation-resources/pull/216
