### ISSUE TITLE
Add support for `excluded_regions` property in Datadog::Integrations::AWS

### ISSUE THREAD

**Issue by pistazie** [DataDog/datadog-cloudformation-resources#223]
We need to exclude AWS regions from our AWS integration.

After contacting support we were advised to use the API and set the `excluded_regions` property ([link](https://docs.datadoghq.com/api/latest/aws-integration/#update-an-aws-integration)).

Unfortunately the AWS resource does not include it so we can't use it.

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/datadog-cloudformation-resources/pull/243

**Comment by adomanov** [comment]
Is this released? It's not currently available in 2.2.1
