### ISSUE TITLE
extraneous key [RenotifyStatuses] is not permitted

### ISSUE THREAD

**Issue by cdelamocepsa** [DataDog/datadog-cloudformation-resources#228]
When I try to deploy the following monitor resource:

```
Resources:
  KinesisMonitor:
    Type: "Datadog::Monitors::Monitor"
    Properties:
      Type: "query alert"
      Query: !Sub "sum(${NotificationWindow}):sum:aws.kinesis.get_records_records.sum{aws_account:${AWS::AccountId},streamname:${KinesisStreamName}}.as_count() <= 0"
      Name: !Sub "mkt-datalake-${Env}-ctr-kinesis-records"
      Message:
        !Join [
          " ",
          [
            "Error en la comunicación CTR - Datalake: No se han recibido transacciones en la ventana temporal",
            !Ref NotificationWindow,
            !Ref NotificationTarget,
          ],
        ]
      Tags:
        - datalake
        - mkt
        - Error en la comunicación CTR - Datalake
        - !Ref Env
        - !Ref AWS::AccountId
      Options:
        Thresholds:
          Critical: !Ref CriticalThreshold
          Warning: !Ref WarningThreshold
        NotifyAudit: false
        Locked: false
        TimeoutH: 0
        NewHostDelay: 300
        RequireFullWindow: false
        RenotifyInterval: 1440
        NotifyNoData: true
        EvaluationDelay: 900
        IncludeTags: true
        RenotifyStatuses:
          - alert
          - no data
        NoDataTimeframe: 480
      DatadogCredentials:
        ApiURL: https://api.datadoghq.eu
        ApiKey: "{{resolve:secretsmanager:DdApiKeySecret-TD}}"
        ApplicationKey: "{{resolve:secretsmanager:DdAppKeySecret-TD}}"

```
I am getting the following CloudFormation Error:

Resource handler returned message: "Model validation failed (#: extraneous key [RenotifyStatuses] is not permitted)" (RequestToken: ef58516d-8c33-422f-7126-628f7a5d9713, HandlerErrorCode: InvalidRequest)

However RenotifyStatuses is admitted in the JsonSchema as per:

https://github.com/DataDog/datadog-cloudformation-resources/blob/d85c1dc0661e33672e938007e4b6d6f6d55f286b/datadog-monitors-monitor-handler/datadog-monitors-monitor.json#L146-L158

**Comment by skarimo** [comment]
Hello, you have an older version of the resource registered. Please update to latest: 4.4.0 (this is the version that introduced support for `RenotifyStatuses`). See: https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/CHANGELOG.md

I am going to close this but feel free to followup/reopen if updating does not resolve your issue.
