### ISSUE TITLE
Permission error while deploying log alert monitor

### ISSUE THREAD

**Issue by bavdh** [DataDog/datadog-cloudformation-resources#266]
**Describe the bug**
I am experiencing an issue while trying to deploy a monitor with the type log alert in Datadog. Although I have provided admin access to the user, I'm encountering a permission error. It's worth mentioning that monitors of other alert types are being deployed successfully without any problems.

Here's a template that i'm using:
```
  AuthPortalForgotPassword:
    Type: 'Datadog::Monitors::Monitor'
    Properties:
      Type: log alert
      Query: "logs(\"@service:authportal @action:forgot-password env:${Env}\").index(\"*\").rollup(\"count\").last(\"5m\") > 7"
      Name: "PartnerPortal: Add customer error (${Env})"
      Message: "{{#is_alert}} High error count on forgot-password and has exceeded the critical threshold. ${SlackChannel}  {{/is_alert}} \n\n{{#is_warning}} Error count on forgot-password has exceeded warning threshold. ${SlackChannel} {{/is_warning}}\n\n{{#is_recovery}} Error count on forgot-password is back to normal level. ${SlackChannel} {{/is_recovery}}"
      Tags:
        - "env:${Env}"
        - "service:authportal"
      Options:
        Thresholds:
          Warning: 0
          Critical: 7
        NotifyNoData: false
```

**To Reproduce**
1. Use the provided template or a similar one with the `log alert` type.
2. Attempt to deploy the monitor.

**Logs**
```
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'date': 'Tue, 13 Jun 2023 09:08:11 GMT', 'content-type': 'application/json', 'vary': 'Accept-Encoding', 'content-encoding': 'gzip', 'x-ratelimit-limit': '500', 'x-ratelimit-period': '10', 'x-ratelimit-remaining': '497', 'x-ratelimit-reset': '9', 'x-ratelimit-name': 'post_monitors', 'x-content-type-options': 'nosniff', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'content-security-policy': "frame-ancestors 'self'; report-uri https://logs.browser-intake-datadoghq.com/api/v2/logs?dd-api-key=<dd-api-key>&dd-evp-origin=content-security-policy&ddsource=csp-report&ddtags=site%3Adatadoghq.eu", 'x-frame-options': 'SAMEORIGIN', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'})
HTTP response body: {'errors': ["User None is missing permission(s) 'logs_read_data'"]}
" (RequestToken: 11d2ce35-0331-7b08-aa3d-79b5fc249367, HandlerErrorCode: AccessDenied)
    at FullCloudFormationDeployment.monitorDeployment (/usr/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:264:24)
    at /usr/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/usr/lib/node_modules/p-queue/dist/index.js:163:29)
 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named WebAppMonitorStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Error creating monitor: (403)
```

**Expected behavior**
Monitor deployment to be successful without any errors.

**Environment and Versions (please complete the following information):**
- Using the Datadog instance in the EU region
- Using Datadog Monitor 4.4.0

**Additional context**
Datadog support has pointed out that the URL in the log above references the US region. However, the api configuration is set to EU. Here is the configuration I'm using:
```
{
  "DatadogCredentials": {
    "ApiKey": "{{resolve:secretsmanager:Datadog:SecretString:SecretAPIKey}}",
    "ApplicationKey": "{{resolve:secretsmanager:Datadog:SecretString:SecretAppKey}}",
    "ApiURL": "https://api.datadoghq.eu"
  }
}
```
Please let me know if there's any further information or troubleshooting steps that I can provide to resolve this issue.

**Comment by skarimo** [comment]
Hi since the error is from the api response, I am inclined to believe this is a valid error and the user is missing the required permissions. Additionally, I did run some tests as well and can confirm this is a permission issue.

I would suggest tracking down the owner of the application key being used to provision the resource and ensuring the user has a role with the permission `logs_read_data`.

**Comment by bavdh** [comment]
I have resolved the issue by removing the scopes from the application key. I was using scopes in the application key, and it turns out that the application key did not have the option for `logs_read_data` permission, which resulted in the error.
