### ISSUE TITLE
Can I migrate existing monitors to CFN

### ISSUE THREAD

**Issue by furstenheim-goodnotes** [DataDog/datadog-cloudformation-resources#272]
**Describe the bug**
I'm just starting to use this extension. And I would like to migrate existing monitors from datadog to CFN.

Since there is an "Id" property in the monitory, I would have expected that it would behave like an upsert. So that I could extract the info of datadog with the api, write everything to cfn and publish.

However, I'm getting 

```
HTTP response body: {'errors': ['Duplicate of an existing monitor_id:111111 org_id:222222']}

```

**To Reproduce**
1. Go to datadog.
2. Create a monitor 
3. Fetch the id from the monitor
4. Create a monitor in CFN (Datadog::Monitors:Monitor) with the same id
5. Try to apply changes

**Expected behavior**
I would expect id in the monitor props to behave as an upsert

**Environment and Versions (please complete the following information):**
I'm using public extension 4.6.0
https://github.com/GoodNotes/cdk-datadog-resources

**Additional context**

**Comment by skarimo** [comment]
Cloudformation doesn't support bringing in resources into cf management by including the primary identifier in the resource definition.

To bring outside resources in to cf, you will need to import the resource during stack creation. See official documentation here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-new-stack.html
