### ISSUE TITLE
Datadog::Integrations::AWS create fails with "create_handler: 'NoneType' object has no attribute 'client'"

### ISSUE THREAD

**Issue by ronaldvaneede** [DataDog/datadog-cloudformation-resources#291]
**Describe the bug**
Creating a Datadog::Integrations::AWS resource fails with:
```Resource handler returned message: "Exception when calling create_handler: 'NoneType' object has no attribute 'client'" (RequestToken: 6e3b8c51-5c97-3c1c-b9dc-51b5d236b038, HandlerErrorCode: null)```
The integration in Datadog itself is being created though.

**To Reproduce**
Following these CLI instructions to install the extension: https://docs.datadoghq.com/integrations/guide/amazon_cloudformation/#aws-command-line-interface
And after defining these resources:
```
  ExternalIDSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub datadog-external-id-${AWSEnvironment}

  AWSAccountIntegration:
    Type: Datadog::Integrations::AWS
    DependsOn: ExternalIDSecret
    Properties:
      ExternalIDSecretName: !Sub datadog-external-id-${AWSEnvironment}
      AccountID: !Ref AWS::AccountId
      RoleName: DatadogIntegration
      HostTags:
        - !Sub "aws_account:${AWS::AccountId}"
        - !Sub "account:${AWSEnvironment}"

  DatadogIntegrationRole:
    Type: AWS::IAM::Role
    DependsOn: AWSAccountIntegration
    Properties:
      RoleName: DatadogIntegration
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref DatadogAWSAccountId
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "{{resolve:secretsmanager:datadog-external-id-${AWSEnvironment}:SecretString}}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Policies:
        - PolicyName: DatadogIntegration
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - apigateway:GET
                  - autoscaling:Describe*
                  - backup:List*
                  - budgets:ViewBudget
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetTrailStatus
                  - cloudtrail:LookupEvents
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - codedeploy:List*
                  - codedeploy:BatchGet*
                  - directconnect:Describe*
                  - dynamodb:List*
                  - dynamodb:Describe*
                  - ec2:Describe*
                  - ecs:Describe*
                  - ecs:List*
                  - elasticache:Describe*
                  - elasticache:List*
                  - elasticfilesystem:DescribeFileSystems
                  - elasticfilesystem:DescribeTags
                  - elasticfilesystem:DescribeAccessPoints
                  - elasticloadbalancing:Describe*
                  - elasticmapreduce:List*
                  - elasticmapreduce:Describe*
                  - es:ListTags
                  - es:ListDomainNames
                  - es:DescribeElasticsearchDomains
                  - events:CreateEventBus
                  - fsx:DescribeFileSystems
                  - fsx:ListTagsForResource
                  - health:DescribeEvents
                  - health:DescribeEventDetails
                  - health:DescribeAffectedEntities
                  - kinesis:List*
                  - kinesis:Describe*
                  - lambda:GetPolicy
                  - lambda:List*
                  - logs:DeleteSubscriptionFilter
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:DescribeSubscriptionFilters
                  - logs:FilterLogEvents
                  - logs:PutSubscriptionFilter
                  - logs:TestMetricFilter
                  - organizations:Describe*
                  - organizations:List*
                  - rds:Describe*
                  - rds:List*
                  - redshift:DescribeClusters
                  - redshift:DescribeLoggingStatus
                  - route53:List*
                  - s3:GetBucketLogging
                  - s3:GetBucketLocation
                  - s3:GetBucketNotification
                  - s3:GetBucketTagging
                  - s3:ListAllMyBuckets
                  - s3:PutBucketNotification
                  - ses:Get*
                  - sns:List*
                  - sns:Publish
                  - sqs:ListQueues
                  - states:ListStateMachines
                  - states:DescribeStateMachine
                  - support:DescribeTrustedAdvisor*
                  - support:RefreshTrustedAdvisorCheck
                  - tag:GetResources
                  - tag:GetTagKeys
                  - tag:GetTagValues
                  - xray:BatchGetTraces
                  - xray:GetTraceSummaries
```
And running cloudformation stack update the error occurs.

**Logs**
```Resource handler returned message: "Exception when calling create_handler: 'NoneType' object has no attribute 'client'" (RequestToken: 6e3b8c51-5c97-3c1c-b9dc-51b5d236b038, HandlerErrorCode: null)```

**Expected behavior**
The resource should be created successfully.

**Environment and Versions (please complete the following information):**
2.4.0

**Comment by skarimo** [comment]
👋 Thanks for reaching out. This is an interesting case and I was not able to reproduce. 

The `client` that is referenced in the error seems to be the boto3 secret manager client retrieved from [here](https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-integrations-aws-handler/src/datadog_integrations_aws/handlers.py#L93). 

The `session` object is initialized and passed from the cloudformation-cli package and we do not have control over this but I would expect it to not be `None`. Could you share the details (trust relationships, policies attached, etc) of the execution role used for `Datadog::Integrations::AWS`. Im thinking there might be a missing relationship or policy and the underlying cloudformation library is unable to initialize the SessionProxy object. 

Regardless, the error you are encountering seems to indicate we cannot assume the session object is always initialized and available. Hence, I will create a PR to store the `ExternalID` in the state and make secret manager non-blocking.

**Comment by ronaldvaneede** [comment]
It must be my fault then if it is caused by permissions.
I was following [these CLI instructions](https://docs.datadoghq.com/integrations/guide/amazon_cloudformation/#aws-command-line-interface) but as I understand now i should set an execution role when with `aws cloudformation register-type` command. This is not mentioned  in those instructions.
I did not do that in my case. If that is it, what policy does that role need?

**Comment by skarimo** [comment]
I have put up this PR to make using SessionProxy optional: https://github.com/DataDog/datadog-cloudformation-resources/pull/292

However if the root cause turns out to be the execution role, I might close the PR and fix the gap in our documentation as well.

Resource role and policies are defined here: https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-integrations-aws-handler/resource-role.yaml

If my memory serves correct, when registering the type, it is suppose to create a an execution role if its not provided but in this case it might not be. Looks like the `register-type` command accepts an optional `--execution-role-arn` option if you would like to use that to attack the new role you have created: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/register-type.html

Additionally, you could you run `describe-type` and check to see if there is a role with correct policies being used: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-type.html

**Comment by ronaldvaneede** [comment]
It was indeed related to the missing execution role. It did not have a default role and after running `register-type` with `--execution-role-arn` using the role from the CF template you linked it did work.

**Comment by skarimo** [comment]
Great, thanks for the feedback. I will close the above PR and fix our documentation!
