### ISSUE TITLE
Deploying `Datadog::Monitors::Monitor` resource results in a rollback due to an Internal Failure.

### ISSUE THREAD

**Issue by yemi-agesin** [DataDog/datadog-cloudformation-resources#311]
Deploying `Datadog::Monitors::Monitor` resource results in a rollback due to an Internal Failure.

**Reproduce**
- Activated Third Pary `Datadog::Monitors::Monitor` extension and inputed the API and APP keys
- Uploading this stack template in cloudformation:

```
Resources:
  DatadogTestMonitor:
    Type: 'Datadog::Monitors::Monitor'
    Properties:
      Type: query alert
      Query: 'avg(last_1h):sum:system.cpu.system{host:host0} > 100'
      Name: Test Monitor
      Options:
        Thresholds:
          Critical: 100
          Warning: 80
          OK: 90
        NotifyNoData: true
        EvaluationDelay: 60
```
- Execution Role Permissions
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "cloudformation.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

**Logs**
Cloudformation just says "Internal Failure. Rollback requested by user.", and Cloudwatch reports no logs

**Expected behavior**
Stack and monitor to be deployed on Datadog

**Comment by yemi-agesin** [comment]
The error was with the execution role permissions. Have to make sure the `Datadog::Monitors::Monitor` resource can access the secrets by enabling it as one of the policies in the execution role.

**Comment by andrewp-svg** [comment]
@yemi-agesin 

Do you mind posting an example snippet of the policy you used to solve this?
