### ISSUE TITLE
Missing Site parameter

### ISSUE THREAD

**Issue by pgarbe** [DataDog/datadog-cloudformation-resources#41]
**Describe the bug**
It's not possible to define in which Site (datadoghq.com or datadoghq.eu) the resources should be created. This is mandatory for users using datadoghq.eu

**Resource Name and version**
* Datadog::Integrations::AWS (v1.0.0)
* Datadog::Monitors::Monitor (v1.0.0)
​* Datadog::Monitors::Downtime (v1.0.0)
* Datadog::IAM::User (v1.0.0)

**Expected behavior**
An optional parameter should be available to specify which DataDog Site should be used. If the parameter is not specified it falls back to the default "datadoghq.com" (like now).

**Comment by bkabrda** [comment]
Hey, we just merged the fix for it - #43. I'm reopening this issue and we'll close it as soon as this is released.

**Comment by pgarbe** [comment]
That's awesome! Looking forward to the release.

**Comment by nmuesch** [comment]
Hey @pgarbe Just wanted to reach back out here and let you know that we released 1.0.1 of the resources yesterday which include support for the new `ApiURL` property. Full Changelog here - https://github.com/DataDog/datadog-cloudformation-resources/blob/master/CHANGELOG.md

Thanks for raising this, and let us know if you experience any issues here.

**Comment by pgarbe** [comment]
Yes, thank you! I tried it already and it worked fine so far. Now, I'm looking forward to #48 and #46 and that the CloudFormation team also supports the new `Type` as CloudFormation resource...
