### ISSUE TITLE
Repo https://github.com/DataDog/datadog-api-client-java does not exist

### ISSUE THREAD

**Issue by sayboras** [DataDog/datadog-cloudformation-resources#44]

**Comment by gzussa** [comment]
Hi, 

Indeed it is not public yet but we are working on it as it should be available soon. Unfortunately, I can't provide you with an ETA yet.

**Comment by sayboras** [comment]
> Hi,
> 
> Indeed it is not public yet but we are working on it as it should be available soon. Unfortunately, I can't provide you with an ETA yet.

Cool, this will definitely help to attract more contribution and make the products more viable :100:. Hope that it will happen soon.
