### ISSUE TITLE
Support for dashboard 

### ISSUE THREAD

**Issue by sayboras** [DataDog/datadog-cloudformation-resources#46]
It would be nice to have support for dashboard as well.

Currently, we need to use our in-house tooling for managing monitoring and dashboard.

**Comment by gzussa** [comment]
At this moment, we only support Users, Monitors, Downtime and AWS Integrations endpoints. More is in the pipeline, including Dashboard and more.

**Comment by gzussa** [comment]
Closing this since we are not keeping feature requests as open issues anymore. See our [contributing.md](CONTRIBUTING.md) doc. 
However more endpoints support is in progress. We will start working on this resource this quarter (Q1 2020).
