### ISSUE TITLE
Support for synthetics tests

### ISSUE THREAD

**Issue by pgarbe** [DataDog/datadog-cloudformation-resources#48]
**Describe the bug**
Have a new CloudFormation resource for synthetic tests

**Resource Name and version**
It's a new resource.

**Expected behavior**
See here: https://docs.datadoghq.com/api/?lang=python#create-a-test

**Comment by gzussa** [comment]
At this moment, we only support Users, Monitors, Downtime and AWS Integrations endpoints. More is in the pipeline, including Synthetics tests and more.

**Comment by gzussa** [comment]
Closing this since we are not keeping feature requests as open issues anymore. See our [contributing.md](CONTRIBUTING.md) doc. 
However more endpoints support is in progress. Unfortunately, I cannot provide an ETA.
