### ISSUE TITLE
DataDog JSON -> CloudFormation YAML

### ISSUE THREAD

**Issue by sojjan1337** [DataDog/datadog-cloudformation-resources#58]
Hi!

Anyone thought building a DataDog JSON -> CloudFormation YAML parser?
There are some available but for TerraForm. example: https://github.com/intercom/datadog-to-terraform

**Comment by gzussa** [comment]
Hi @sojjan1337, 

This is not planned. 
At the moment, our focus is to support as many endpoints as possible. 
For feature request, I suggest you contact our support team. See the [SUPPORT.md](SUPPORT.md) file for details.
