### ISSUE TITLE
Datadog::Monitors::Monitor Failing to Update 

### ISSUE THREAD

**Issue by allistera** [DataDog/datadog-cloudformation-resources#72]
**Describe the bug**

We have a cloud formation stack with a number of Monitor resources in it. When updating this stack, for example updating the 'message' property the Resource it fails due to the following reason:

`Handler returned a new physical resource identifier during update.`

This does not happen all the time - it usually happens when some time has passed since the stack was last updated/created.

We suspect this is due to the monitors changing on the datadog side, perhaps its state. 

**To Reproduce**
1. Create a CF stack with monitor on it
2. Wait until the monitor changes state on datadog side
3. Update the CF stack

**Expected behavior**
Stack updates

**Comment by bkabrda** [comment]
Hey 👋 thanks for the issue report.

I'm having a hard time seeing how this might happen, as monitor ids don't change on Datadog side. My current working theory is that this might have something to do with the fact that we convert the monitor id from `long` (which is what the DD API client returns) to `double` (which is what the Id type is set to in cloudformation). This might theoretically result into the `double` values comparison returning false sometimes if they're not compared properly on AWS side. I don't have access to the code that does the comparison, so I'll try to contact AWS folks and discuss with them.

When this happens on a monitor, does it keep happening for it consistently? Or does the update sometimes succeed? If it succeeds sometimes, that might confirm my theory.

As a side note, we had to choose double to represent the Id as it was (and still is not AFAICS) possible to choose `long`.

**Comment by allistera** [comment]
Hi @bkabrda  - Yes it does update occasionally, it seems to be if updating an existing stack that has existed for over a few minutes.

**Comment by bkabrda** [comment]
Hey, sorry for the delay on this. I finally got around to testing this. I haven't managed to reproduce the issue yet, but I'll try for couple of days with some additional logging to see what's going on there. I think maybe the biggest issue is that we use `model.setId()` in the read handlers, where there's no reason to do this in the first place, because the Id of the read resource can't really change (as we've just read it using that Id). So I think eventually the solution will be to not call `model.setId()`, but I'd like to see what's going on in there first.

**Comment by rjlohan** [comment]
FWIW, the reason you're seeing this error is in relation to this part of the [Handler Contract](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html;)

> The primaryIdentifier property value MUST NOT be changed during an update operation. Changing the primaryIdentifier property value implies that the resource itself has been replaced.

**Comment by rjlohan** [comment]
> Hey, sorry for the delay on this. I finally got around to testing this. I haven't managed to reproduce the issue yet, but I'll try for couple of days with some additional logging to see what's going on there. I think maybe the biggest issue is that we use `model.setId()` in the read handlers, where there's no reason to do this in the first place, because the Id of the read resource can't really change (as we've just read it using that Id). So I think eventually the solution will be to not call `model.setId()`, but I'd like to see what's going on in there first.

[This](https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/src/main/java/com/datadog/monitors/monitor/ReadHandler.java#L57) seems likely the culprit as you've identified.

If you observe here that the ID is _not_ changing, yet you still see this error, please raise an issue against the https://github.com/aws-cloudformation/aws-cloudformation-rpdk-java-plugin repo and I'll chase it down on the CFN side.

**Comment by bkabrda** [comment]
Hey @allistera, I've just released a new version of the Monitor resource (2.0.0), so feel free to try it out. You can either get it from the [GH release page]() or the S3 link mentioned in the [changelog entry](https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/CHANGELOG.md#200). Please let me know how this works.

(FTR, it seems that once you create a stack using a version of a resource, it's not possible to update that given stack to use a newer version of that resource, so you'll likely need to create a new stack - @rjlohan please correct me if I'm wrong here.)

**Comment by allistera** [comment]
We have tested this in our pipeline and the stacks are successfully updating.

Big thanks to everyone!
