### ISSUE TITLE
Use latest release of datadog-api-client-java

### ISSUE THREAD

**Issue by bengglim** [DataDog/datadog-cloudformation-resources#73]
Hi 👋, this repository is using a non public version of datadog-api-client-java. This makes it very hard to contribute to this project. What are your thoughts for using [1.0.0.beta.2](https://github.com/DataDog/datadog-api-client-java/releases/tag/datadog-api-client-1.0.0-beta.2)? I'm happy to create a PR for this.

**Comment by bkabrda** [comment]
Hey @bengglim I've just merged PR #74 which updates to 1.0.0.beta3, which is the latest release. Do note that the client is still in beta, so things may change/disappear before the 1.0.0 final release.
