### ISSUE TITLE
Return Physical ID of CloudFormation resource DataDog::Monitors::Monitor in non-scientific form

### ISSUE THREAD

**Issue by azec-pdx** [DataDog/datadog-cloudformation-resources#80]
**NOTE**: I have initially commented about this in #62 , but since it is not fixing that issue in broader sense I have decided to open separate issue to be able to contribute.

**ISSUE**: The `Physical ID` of `DataDog::Monitoring::Monitor` resource is returned in useless scientific notation which complicates its further use in CloudFormation templates. 

<img width="1215" alt="datadog-return-monitor-id-in-sci-notation" src="https://user-images.githubusercontent.com/1272830/88624746-5df30e00-d05c-11ea-9f9d-d1400735cade.png">

Here is my use case:

Defining two basic DataDog Monitor resources with "**query alert**" type, and then trying to define third Composite monitor which would use previous two. Composite monitor should have query "monitor1DataDogID && monitor2DataDogID". Instead of being able to use PhysicalResourceID as ID attribute of first two stacked DataDog Monitor resources (with use of `!GetAtt DatadogMongoDBCPUIOWaitHighMonitor.ID` and with use of `!GetAtt DatadogMongoDBCachedMemoryLowMonitor.ID`) , I had to hack around with value which DataDog Third-Party CF Resource currently returns as PhysicalResourceID. For example , if DataDog Monitor resource is created through CloudFormation and in DataDog belonging monitor has ID `12345678`, then corresponding `PhysicalResourceId` of that resource in CloudFormation will have value `1.2345678E7` (skewed, malformed number which is not whole number and therefore unusable string of DataDog Monitor ID). 

Basic monitor 1
```
DatadogMongoDBCPUIOWaitHighMonitor:
    Type: Datadog::Monitors::Monitor
    Properties:
      Type: query alert
      Query: !Sub 'avg(last_1m):avg:system.cpu.iowait{replicasetname:${Domain},environment:${environment}} by {host} > 10'
      Name: !Sub 'mongocluster-${Domain}-${environment}: CPU IOwait {{value}} [%] {{comparator}} 10 [%] for host {{host.name}}'
      Message: |
        {{#is_alert}}

        To fix follow these steps:


          1. Check status health of replica in <URL_REDACTED>
          2. If any alerts are active in Mongo Cloud Health, acknowledge them in PagerDuty
          3. Reach out to the team owning this MongoDB domain and look for utilization peaks in Mongo Cloud Health manager!
          4. Try to remediate root cause of the CPU waits spike asap !
          5. Observe memory utilization in response to your remediation actions !
          6. Login to AWS Console in `<REDACTED>` and troubleshoot the instance state:
              3a. check if you can ssh into the node
              3b. check if docker container is running
              3c. check if we had AWS hardware degradation e-mail related to this EC2 instance
        {{/is_alert}}

        {{#is_recovery}}
         Host {{host.name}} is back to normal CPU IO wait with value of {{value}}%!
        {{/is_recovery}}

        Notify: @pagerduty-GlobalPDRouting
        More Information On How This Alert Was Setup: [Incident Management with Pager Duty](<URL_REDACTED>)
      Options:
        Thresholds:
          Critical: 10
          OK: 9.99
          CriticalRecovery: 9.99
        NotifyNoData: false
        RequireFullWindow: true
        NewHostDelay: 120
      DatadogCredentials:
        ApiKey: '{{resolve:secretsmanager:<REDACTED>:apikey}}'
        ApplicationKey: '{{resolve:secretsmanager:<REDACTED>:SecretString:applicationkey}}'
```

Basic monitor 2

```
DatadogMongoDBCachedMemoryLowMonitor:
    Type: Datadog::Monitors::Monitor
    Properties:
      Type: query alert
      Query: !Sub 'avg(last_1m):avg:system.mem.cached{replicasetname:${Domain},environment:${environment}} by {host} < 500000000'
      Name: !Sub 'mongocluster-${Domain}-${environment}: Cached memory {{value}} [B] {{comparator}} 500 [MB] for host {{host.name}}'
      Message: |
        {{#is_alert}}

        To fix follow these steps:

          1. Check status health of replica in <URL_REDACTED>
          2. If any alerts are active in Mongo Cloud Health, acknowledge them in PagerDuty
          3. Reach out to the team owning this MongoDB domain and look for utilization peaks in Mongo Cloud Health manager!
          4. Try to remediate root cause of the low system cache asap !
          5. Observe memory utilization in response to your remediation actions !
          6. Login to AWS Console in `<REDACTED>` and troubleshoot the instance state:
              3a. check if you can ssh into the node
              3b. check if docker container is running
              3c. check if we had AWS hardware degradation e-mail related to this EC2 instance
        {{/is_alert}}

        {{#is_recovery}}
         Host {{host.name}} is back to normal values for cached system memory with value of {{value}}!
        {{/is_recovery}}

        Notify: @pagerduty-GlobalPDRouting
        More Information On How This Alert Was Setup: [Incident Management with Pager Duty](<URL_REDACTED>)
      Options:
        Thresholds:
          Critical: 500000000
          OK: 500000001
          CriticalRecovery: 500000001
        NotifyNoData: false
        RequireFullWindow: true
        NewHostDelay: 120
      DatadogCredentials:
        ApiKey: '{{resolve:secretsmanager:<REDACTED>:SecretString:apikey}}'
        ApplicationKey: '{{resolve:secretsmanager:<REDACTED>:SecretString:applicationkey}}'
```

I would like my third, composite monitor (attention on `Query` property below) to be defined as:

```
DatadogMongoDBSwappingWatchCompositeMonitor:
    Type: Datadog::Monitors::Monitor
    DependsOn: [DatadogMongoDBCPUIOWaitHighMonitor, DatadogMongoDBCachedMemoryLowMonitor]
    Properties:
      Type: composite
--> Query: !Sub "${DatadogMongoDBCPUIOWaitHighMonitor} && ${DatadogMongoDBCachedMemoryLowMonitor}"
      Name: !Sub 'mongocluster-${Domain}-${environment}: High IOWait and low system cached memory - potential swapping on host {{host.name}}'
      Message: |
        {{#is_alert}}

        There are other two independent alarms for "system.mem.cached" and "system.cpu.iowait" metrics setup - you should check them out (they have same prefix as this monitor) !!!

        To fix follow these steps:


          1. Check status health of replica in <URL_REDACTED>
          2. If any alerts are active in Mongo Cloud Health, acknowledge them in PagerDuty
          3. Reach out to the team owning this MongoDB domain and look for utilization peaks in Mongo Cloud Health manager!
          4. Try to remediate root cause for swapping asap !
          5. Observe memory utilization in response to your remediation actions !
          6. Login to AWS Console in `<REDACTED>` and troubleshoot the instance state:
              3a. check if you can ssh into the node
              3b. check if docker container is running
              3c. check if we had AWS hardware degradation e-mail related to this EC2 instance
        {{/is_alert}}

        {{#is_recovery}}
         Host {{host.name}} potential swapping back to normal !
        {{/is_recovery}}

        Notify: @pagerduty-GlobalPDRouting
        More Information On How This Alert Was Setup: [Incident Management with Pager Duty](<URL_REDACTED>)
      Options:
        NotifyNoData: false
      DatadogCredentials:
        ApiKey: '{{resolve:secretsmanager:<REDACTED>:SecretString:apikey}}'
        ApplicationKey: '{{resolve:secretsmanager:<REDACTED>:SecretString:applicationkey}}'

```

... instead I had to hack around the returned value for Physical ID of  `Datadog::Monitors::Monitor` CF resource ( again, attention is on `Query` property below), with ...

```
DatadogMongoDBSwappingWatchCompositeMonitor:
    Type: Datadog::Monitors::Monitor
    DependsOn: [DatadogMongoDBCPUIOWaitHighMonitor, DatadogMongoDBCachedMemoryLowMonitor]
    Properties:
      Type: composite
      Query: !Sub
          - "${DatadogMongoDBCPUIOWaitHighMonitorID} && ${DatadogMongoDBCachedMemoryLowMonitorID}"
          - DatadogMongoDBCPUIOWaitHighMonitorID:  !Select [ 0, !Split ["E7", !Join [ "", !Split [ "." , !Ref DatadogMongoDBCPUIOWaitHighMonitor ]] ] ]
            DatadogMongoDBCachedMemoryLowMonitorID: !Select [ 0, !Split ["E7", !Join [ "", !Split [ "." , !Ref DatadogMongoDBCachedMemoryLowMonitor ]] ] ]
      Name: !Sub 'mongocluster-${Domain}-${environment}: High IOWait and low system cached memory - potential swapping on host {{host.name}}'
      Message: |
        {{#is_alert}}

        There are other two independent alarms for "system.mem.cached" and "system.cpu.iowait" metrics setup - you should check them out (they have same prefix as this monitor) !!!

        To fix follow these steps:


          1. Check status health of replica in <URL_REDACTED>
          2. If any alerts are active in Mongo Cloud Health, acknowledge them in PagerDuty
          3. Reach out to the team owning this MongoDB domain and look for utilization peaks in Mongo Cloud Health manager!
          4. Try to remediate root cause for swapping asap !
          5. Observe memory utilization in response to your remediation actions !
          6. Login to AWS Console in `<REDACTED>` and troubleshoot the instance state:
              3a. check if you can ssh into the node
              3b. check if docker container is running
              3c. check if we had AWS hardware degradation e-mail related to this EC2 instance
        {{/is_alert}}

        {{#is_recovery}}
         Host {{host.name}} potential swapping back to normal !
        {{/is_recovery}}

        Notify: @pagerduty-GlobalPDRouting
        More Information On How This Alert Was Setup: [Incident Management with Pager Duty](<URL_REDACTED>)
      Options:
        NotifyNoData: false
      DatadogCredentials:
        ApiKey: '{{resolve:secretsmanager:<REDACTED>:SecretString:apikey}}'
        ApplicationKey: '{{resolve:secretsmanager:<REDACTED>:SecretString:applicationkey}}'
```

**Comment by azec-pdx** [comment]
Hi @jirikuncar , I am trying to get some traction with this issue. I have PR https://github.com/DataDog/datadog-cloudformation-resources/pull/81 opened for this.

**Comment by bkabrda** [comment]
So I think the proposal in PR #81 is ok. However, I think the best solution would be to have a way to generate integers as `Long` values, which the current code is working around by using `number` (which gets generated as `Double`). There is an open issue for this in https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/151 and I just commented on it in https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/151#issuecomment-667990664. @azec-pdx can you confirm that having ID as `Long` would work ok for you (assuming the AWS folks decide to implement it)?

**Comment by azec-pdx** [comment]
> So I think the proposal in PR #81 is ok. However, I think the best solution would be to have a way to generate integers as `Long` values, which the current code is working around by using `number` (which gets generated as `Double`). There is an open issue for this in [aws-cloudformation/cloudformation-cli-java-plugin#151](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/151) and I just commented on it in [aws-cloudformation/cloudformation-cli-java-plugin#151 (comment)](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/151#issuecomment-667990664). @azec-pdx can you confirm that having ID as `Long` would work ok for you (assuming the AWS folks decide to implement it)?

Hey @bkabrda , I saw your comment on [aws-cloudformation/cloudformation-cli-java-plugin#151 (comment)](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/151#issuecomment-667990664).
I was not aware of the attempt to make this improvement long-term in the Java CLI plugin for CloudFormation toolkit.

To answer your question, yes, we can live for now without this being merged while waiting for IDs to be generated as `Long` type inside CLI. At this point, I was able to build new version of this Third-Party resource locally and update our CloudFormation registry with new Schema definition to include this short-term fix. Long-term, we would be glad if AWS team makes proposed change - I hope we get some traction on that PR on their side.

**Comment by nmuesch** [comment]
Hey @azec-pdx We just released a beta version of a new Major for the monitor resource - https://github.com/DataDog/datadog-cloudformation-resources/releases/tag/datadog-monitors-monitor-3.0.0b1
This includes a change to the internal runtime language from java -> python, as well as a schema change around how ints are used. This should provide a physical id that isn't in scientific notation. Could you give this version a try and see if it addresses your use case?

**Comment by nmuesch** [comment]
@azec-pdx I'll go ahead and close this out as this should be resolved with the recent python migration and schema change. Thanks for the detailed report and the work put in to look for a workaround! 
Let us know if you continue to experience any issues here!
