### ISSUE TITLE
Put current version into the description

### ISSUE THREAD

**Issue by elruwen** [DataDog/datadog-cloudformation-resources#87]
Hi!

Currently the description of the resource says only "Datadog Monitor". I would prefer it to say "Datadog Monitor 2.1.0" so i know which version is deployed. Otherwise I need to keep track of the version somewhere somehow myself.

**Is your feature request related to a problem? Please describe.**
When I want to find out which version of the cloudformation type I have deployed, I can't:
```
aws cloudformation list-type-versions --region my-region --type RESOURCE --type-name "Datadog::Monitors::Monitor" 
{
    "TypeVersionSummaries": [
        {
            "Type": "RESOURCE",
            "TypeName": "Datadog::Monitors::Monitor",
            "VersionId": "00000001",
            "IsDefaultVersion": true,
            "Arn": "arn:aws:cloudformation:xxxxxxxx/resource/Datadog-Monitors-Monitor/00000001",
            "Description": "Datadog Monitor"
        }
    ]
}
```

**Describe the solution you'd like**
Add the version to the description:
```
aws cloudformation list-type-versions --region my-region --type RESOURCE --type-name "Datadog::Monitors::Monitor" 
{
    "TypeVersionSummaries": [
        {
            "Type": "RESOURCE",
            "TypeName": "Datadog::Monitors::Monitor",
            "VersionId": "00000001",
            "IsDefaultVersion": true,
            "Arn": "arn:aws:cloudformation:xxxxxxxx/resource/Datadog-Monitors-Monitor/00000001",
            "Description": "Datadog Monitor 2.1.0"
        }
    ]
}
```

**Describe alternatives you've considered**
My maintaining somewhere a list which says:
aws account id + version id => 2.1.0

**Additional context**
n/a

**Comment by elruwen** [comment]
I still got this request.

**Comment by nmuesch** [comment]
Hey @elruwen apologies for the delay here. Thanks for the request. I have a PR #97 that will include the version in the descriptions
